import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header
          navigationData={[
            {
              title: "Articles",
              href: "/",
            },
            // {
            //   title: "Products",
            //   href: "#",
            // },
            // {
            //   title: "About Us",
            //   href: "#",
            // },
            // {
            //   title: "Contacts",
            //   href: "#",
            // },
          ]}
        /> */}
        {children}
      </body>
    </html>
  );
}
